In [1]:
import numpy as np
import pandas as pd

In [2]:
match = pd.read_csv('matches.csv')
delivery = pd.read_csv('deliveries.csv')

In [3]:
match.head()

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,IPL-2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,IPL-2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN

In [4]:
match.shape

(756, 18)

In [5]:
delivery.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [6]:
total_score_df = delivery.groupby(['match_id','inning']).sum()['total_runs'].reset_index()

In [7]:
total_score_df = total_score_df[total_score_df['inning'] == 1]

In [8]:
total_score_df

      match_id  inning  total_runs
0            1       1         207
2            2       1         184
4            3       1         183
6            4       1         163
8            5       1         157
10           6       1         135
12           7       1         178
14           8       1         148
16           9       1         205
18          10       1         158
20          11       1         170
22          12       1         142
24          13       1         171
26          14       1         172
28          15       1         188
30          16       1         176
32          17       1         161
34          18       1         168
36          19       1         159
38          20       1         213
40          21       1         191
42          22       1         198
44          23       1         187
46          24       1         142
48          25       1         176
50          26       1         188
52          27       1         131
54          28       1         160
56          29       1         182
58          30       1         134
...        ...     ...         ...
1466     11322       1         179
1468     11323       1         190
1470     11324       1         139
1472     11325       1         174
1474     11326       1         219
1476     11327       1         171
1478     11328       1         168
1480     11329       1         164
1482     11330       1         165
1484     11331       1         196
1486     11332       1         179
1488     11333       1         213
1490     11334       1         185
1492     11335       1         159
1494     11336       1         169
1496     11337       1         193
1498     11338       1         241
1500     11339       1         232
1502     11340       1          65
1504     11341       1         186
1506     11342       1         170
1510     11343       1         186
1512     11344       1         124
1514     11345       1         179
1516     11346       1         172
1518     11347       1         143
1520     11412       1         136
1522     11413       1         171
1524     11414       1         155
1526     11415       1         152

[756 rows x 3 columns]

In [9]:
match_df = match.merge(total_score_df[['match_id','total_runs']],left_on='id',right_on='match_id')

In [10]:
match_df

,id,Season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3,match_id,total_runs
0,1,IPL-2017,Hyderabad,05-04-2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN,1,207
1,2,IPL-2017,Pune,06-04-2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN,2,184
2,3,IPL-2017,Rajkot,07-04-2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN,3,183
3,4,IPL-2017,Indore,08-04-2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN,4,163
4,5,IPL-2017,Bangalore,08-04-2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN,5,157
5,6,IPL-2017,Hyderabad,09-04-2017,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,9,Rashid Khan,"Rajiv Gandhi International Stadium, Uppal",A Deshmukh,NJ Llong,NaN,6,135
6,7,IPL-2017,Mumbai,09-04-2017,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,N Rana,Wankhede Stadium,Nitin Menon,CK Nandan,NaN,7,178
7,8,IPL-2017,Indore,10-04-2017,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,normal,0,Kings XI Punjab,0,8,AR Patel,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN,8,148
8,9,IPL-2017,Pune,11-04-2017,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Delhi Daredevils,97,0,SV Samson,Maharashtra Cricket Association Stadium,AY Dandekar,S Ravi,NaN,9,205
9,10,IPL-2017,Mumbai,12-04-2017,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,JJ Bumrah,Wankhede Stadium,Nitin Menon,CK Nandan,NaN,10,158
10,11,IPL-2017,Kolkata,13-04-2017,Kings XI Punjab,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,8,SP Narine,Eden Gardens,A Deshmukh,NJ Llong,NaN,11,170
11,12,IPL-2017,Bangalore,14-04-2017,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,KA Pollard,M Chinnaswamy Stadium,KN Ananthapadmanabhan,AK Chaudhary,NaN,12,142
12,13,IPL-2017,Rajkot,14-04-2017,Rising Pune Supergiant,Gujarat Lions,Gujarat Lions,field,normal,0,Gujarat Lions,0,7,AJ Tye,Saurashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN,13,171
13,14,IPL-2017,Kolkata,15-04-2017,Kolkata Knight Riders,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Kolkata Knight Riders,17,0,RV Uthappa,Eden Gardens,AY Dandekar,NJ Llong,NaN,14,172
14,15,IPL-2017,Delhi,15-04-2017,Delhi Daredevils,Kings XI Punjab,Delhi Daredevils,bat,normal,0,Delhi Daredevils,51,0,CJ Anderson,Feroz Shah Kotla,YC Barde,Nitin Menon,NaN,15,188
15,16,IPL-2017,Mumbai,16-04-2017,Gujarat Lions,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,6,N Rana,Wankhede Stadium,A Nand Kishore,S Ravi,NaN,16,176
16,17,IPL-2017,Bangalore,16-04-2017,Rising Pune Supergiant,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Rising Pune Supergiant,27,0,BA Stokes,M Chinnaswamy Stadium,KN Ananthapadmanabhan,C Shamshuddin,NaN,17,161
17,18,IPL-2017,Delhi,17-04-2017,Delhi Daredevils,Kolkata Knight Riders,Delhi Daredevils,bat,normal,0,Kolkata Knight Riders,0,4,NM Coulter-Nile,Feroz Shah Kotla,Nitin Menon,CK Nandan,NaN,18,168
18,19,IPL-2017,Hyderabad,17-04-2017,Sunrisers Hyderabad,Kings XI Punjab,Kings XI Punjab,field,normal,0,Sunrisers Hyderabad,5,0,B Kumar,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,A Deshmukh,NaN,19,159
19,20,IPL-2017,Rajkot,18-04-2017,Royal Challengers Bangalore,Gujarat Lions,Gujarat Lions,field,normal,0,Royal Challengers Bangalore,21,0,CH Gayle,Saurashtra Cricket Association Stadium,S Ravi,VK Sharma,NaN,20,213
20,21,IPL-2017,Hyderabad,19-04-2017,Sunrisers Hyderabad,Delhi Daredevils,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,15,0,KS Williamson,"Rajiv Gandhi International Stadium, Uppal",CB Gaffaney,NJ Llong,NaN,21,191
21,22,IPL-2017,Indore,20-04-2017,Kings XI Punjab,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,8,JC Buttler,Holkar Cricket Stadium,M Erasmus,C Shamshuddin,NaN,22,198
22,23,IPL-2017,Kolkata,21-04-2017,Kolkata Knight Riders,Gujarat Lions,Gujarat Lions,field,normal,0,Gujarat Lions,0,4,SK Raina,Eden Gardens,CB Gaffaney,Nitin Menon,NaN,23,187
23,24,IPL-2017,Mumbai,22-04-2017,Mumbai Indians,Delhi Daredevils,Delhi Daredevils,field,normal,0,Mumbai Indians,14,0,MJ McClenaghan,Wankhede Stadium,A Nand Kishore,S Ravi,NaN,24,142
24,25,IPL-2017,Pune,22-04-2017,Sunrisers Hyderabad,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,6,MS Dhoni,Maharashtra Cricket Association Stadium,AY Dandekar,A Deshmukh,NaN,25,176
25,26,IPL-2017,Rajkot,23-04-2017,Kings XI Punjab,Gujarat Lions,Gujarat Lions,field,normal,0,Kings XI Punjab,26,0,HM Amla,Saurashtra Cricket Association Stadium,AK Chaudhary,M Erasmus,NaN,26,188
26,27,IPL-2017,Kolkata,23-04-2017,Kolkata Knight Riders,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Kolkata Knight Riders,82,0,NM Coulter-Nile,Eden Gardens,CB Gaffaney,CK Nandan,NaN,27,131
27,28,IPL-2017,Mumbai,24-04-2017,Rising Pune Supergiant,Mumbai Indians,Mumbai Indians,field,normal,0,Rising Pune Supergiant,3,0,BA Stokes,Wankhede Stadium,A Nand Kishore,S Ravi,NaN,28,160
28,29,IPL-2017,Pune,26-04-2017,Rising Pune Supergiant,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,7,RV Uthappa,Maharashtra Cricket Association Stadium,AY Dandekar,NJ Llong,NaN,29,182
29,30,IPL-2017,Bangalore,27-04-2017,Royal Challengers Bangalore,Gujarat Lions,Gujarat Lions,field,normal,0,Gujarat Lions,0,7,AJ Tye,M Chinnaswamy Stadium,AK Chaudhary,C Shamshuddin,NaN,30,134
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,11322,IPL-2019,Mumbai,15-04-2019,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,5,SL Malinga,Wankhede Stadium,Marais Erasmus,Nitin Menon,Nanda Kishore,11322,179
727,11323,IPL-2019,Mohali,16-04-2019,Kings XI Punjab,Rajasthan Royals,Rajasthan Royals,field,normal,0,Kings XI Punjab,12,0,R Ashwin,IS Bindra Stadium,Anil Chaudhary,Vineet Kulkarni,S Ravi,11323,190
728,11324,IPL-2019,Hyderabad,17-04-2019,Chennai Super Kings,Sunrisers Hyderabad,Chennai Super Kings,bat,normal,0,Sunrisers Hyderabad,0,6,DA Warner,Rajiv Gandhi Intl. Cricket Stadium,Ian Gould,Ulhas Gandhe,C Shamshuddin,11324,139
729,11325,IPL-2019,Delhi,18-04-2019,Mumbai Indians,Delhi Capitals,Mumbai Indians,bat,normal,0,Mumbai Indians,40,0,HH Pandya,Feroz Shah Kotla Ground,Nigel Llong,Bruce Oxenford,Anil Chaudhary,11325,174
730,11326,IPL-2019,Kolkata,19-04-2019,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Royal Challengers Bangalore,10,0,V Kohli,Eden Gardens,Ian Gould,Nitin Menon,Anil Dandekar,11326,219
731,11327,IPL-2019,Jaipur,20-04-2019,Mumbai Indians,Rajasthan Royals,Rajasthan Royals,field,normal,0,Rajasthan Royals,0,5,SPD Smith,Sawai Mansingh Stadium,S Ravi,Yeshwant Barde,O Nandan,11327,171
732,11328,IPL-2019,Delhi,20-04-2019,Kings XI Punjab,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,5,SS Iyer,Feroz Shah Kotla Ground,Ulhas Gandhe,C Shamshuddin,Bruce Oxenford,11328,168
733,11329,IPL-2019,Hyderabad,21-04-2019,Kolkata Knight Riders,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,9,K Ahmed,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Nigel Llong,Ian Gould,11329,164
734,11330,IPL-2019,Bengaluru,21-04-2019,Royal Challengers Bangalore,Chennai Super Kings,Chennai Super Kings,field,normal,0,Royal Challengers Bangalore,1,0,PA Patel,M. Chinnaswamy Stadium,Vineet Kulkarni,Rod Tucker,Anil Chaudhary,11330,165
735,11331,IPL-2019,Jaipur,22-04-2019,Rajasthan Royals,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,6,RR Pant,Sawai Mansingh Stadium,S Ravi,Nanda Kishore,Yeshwant Barde,11331,196
736,11332,IPL-2019,Chennai,23-04-2019,Sunrisers Hyderabad,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,SR Watson,M. A. Chidambaram Stadium,Nigel Llong,Anil Chaudhary,Vineet Kulkarni,11332,179
737,11333,IPL-2019,Bengaluru,24-04-2019,Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab,field,normal,0,Royal Challengers Bangalore,17,0,AB de Villiers,M. Chinnaswamy Stadium,Bruce Oxenford,C Shamshuddin,Rod Tucker,11333,213
738,11334,IPL-2019,Kolkata,25-04-2019,Kolkata Knight Riders,Rajasthan Royals,Rajasthan Royals,field,normal,0,Rajasthan Royals,0,3,VR Aaron,Eden Gardens,Ian Gould,Anil Dandekar,Nitin Menon,11334,185
739,11335,IPL-2019,Chennai,26-04-2019,Mumbai Indians,Chennai Super Kings,Chennai Super Kings,field,normal,0,Mumbai Indians,46,0,RG Sharma,M. A. Chidambaram Stadium,Nigel Llong,Anil Chaudhary,Vineet Kulkarni,11335,159
740,11336,IPL-2019,Jaipur,27-04-2019,Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,field,normal,0,Rajasthan Royals,0,7,JD Unadkat,Sawai Mansingh Stadium,Yeshwant Barde,Nand Kishore,Sundaram Ravi,11336,169
741,11337,IPL-2019,Delhi,28-04-2019,Delhi Capitals,Royal Challengers Bangalore,Delhi Capitals,bat,normal,0,Delhi Capitals,16,0,S Dhawan,Feroz Shah Kotla Ground,Bruce Oxenford,KN Ananthapadmanabhan,C Shamshuddin,11337,193
742,11338,IPL-2019,Kolkata,28-04-2019,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Kolkata Knight Riders,34,0,AD Russell,Eden Gardens,Ian Gould,Nitin Menon,Anil Dandekar,11338,241
743,11339,IPL-2019,Hyderabad,29-04-2019,Sunrisers Hyderabad,Kings XI Punjab,Kings XI Punjab,field,normal,0,Sunrisers Hyderabad,45,0,DA Warner,Rajiv Gandhi Intl. Cricket Stadium,S Ravi,O Nandan,Nanda Kishore,11339,232
744,11340,IPL-2019,Bengaluru,30-04-2019,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,no result,0,NaN,0,0,NaN,M. Chinnaswamy Stadium,Nigel Llong,Ulhas Gandhe,Anil Chaudhary,11340,65
745,11341,IPL-2019,Chennai,01-05-2019,Chennai Super Kings,Delhi Capitals,Delhi Capitals,field,normal,0,Chennai Super Kings,80,0,MS Dhoni,M. A. Chidambaram Stadium,Anil Dandekar,Nitin Menon,Ian Gould,11341,186
746,11342,IPL-2019,Mumbai,02-05-2019,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,bat,tie,0,Mumbai Indians,0,0,JJ Bumrah,Wankhede Stadium,S Ravi,O Nandan,Nanda Kishore,11342,170
747,11343,IPL-2019,Mohali,03-05-2019,Kings XI Punjab,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,7,S Gill,IS Bindra Stadium,Bruce Oxenford,C Shamshuddin,KN Ananthapadmanabhan,11343,186
748,11344,IPL-2019,Delhi,04-05-2019,Rajasthan Royals,Delhi Capitals,Rajasthan Royals,bat,normal,0,Delhi Capitals,0,5,A Mishra,Feroz Shah Kotla Ground,Ian Gould,Anil Dandekar,Nitin Menon,11344,124
749,11345,IPL-2019,Bengaluru,04-05-2019,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,S Hetmyer,M. Chinnaswamy Stadium,Nigel Llong,Anil Chaudhary,Ulhas Gandhe,11345,179
750,11346,IPL-2019,Mohali,05-05-2019,Chennai Super Kings,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,KL Rahul,IS Bindra Stadium,KN Ananthapadmanabhan,C Shamshuddin,Bruce Oxenford,11346,172
751,11347,IPL-2019,Mumbai,05-05-2019,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,HH Pandya,Wankhede Stadium,Nanda Kishore,O Nandan,S Ravi,11347,143
752,11412,IPL-2019,Chennai,07-05-2019,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,0,6,AS Yadav,M. A. Chidambaram Stadium,Nigel Llong,Nitin Menon,Ian Gould,11412,136
753,11413,IPL-2019,Visakhapatnam,08-05-2019,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN,NaN,11413,171
754,11414,IPL-2019,Visakhapatnam,10-05-2019,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,F du Plessis,ACA-VDCA Stadium,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin,11414,155
755,11415,IPL-2019,Hyderabad,12-05-2019,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong,11415,152

In [11]:
match_df['team1'].unique()

array(['Sunrisers Hyderabad', 'Mumbai Indians', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Royal Challengers Bangalore',
       'Kolkata Knight Riders', 'Delhi Daredevils', 'Kings XI Punjab',
       'Chennai Super Kings', 'Rajasthan Royals', 'Deccan Chargers',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Rising Pune Supergiants',
       'Delhi Capitals'], dtype=object)

In [12]:
teams = [
    'Sunrisers Hyderabad',
    'Mumbai Indians',
    'Royal Challengers Bangalore',
    'Kolkata Knight Riders',
    'Kings XI Punjab',
    'Chennai Super Kings',
    'Rajasthan Royals',
    'Delhi Capitals'
]

In [13]:
match_df['team1'] = match_df['team1'].str.replace('Delhi Daredevils','Delhi Capitals')
match_df['team2'] = match_df['team2'].str.replace('Delhi Daredevils','Delhi Capitals')

match_df['team1'] = match_df['team1'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
match_df['team2'] = match_df['team2'].str.replace('Deccan Chargers','Sunrisers Hyderabad')

In [14]:
match_df = match_df[match_df['team1'].isin(teams)]
match_df = match_df[match_df['team2'].isin(teams)]

In [15]:
match_df.shape

(641, 20)

In [16]:
match_df = match_df[match_df['dl_applied'] == 0]

In [17]:
match_df = match_df[['match_id','city','winner','total_runs']]

In [18]:
delivery_df = match_df.merge(delivery,on='match_id')

In [19]:
delivery_df = delivery_df[delivery_df['inning'] == 2]

In [20]:
delivery_df

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs_y,player_dismissed,dismissal_kind,fielder
125,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,...,0,0,0,0,1,0,1,NaN,NaN,NaN
126,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,Mandeep Singh,...,0,0,0,0,0,0,0,NaN,NaN,NaN
127,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,3,Mandeep Singh,...,0,0,0,0,0,0,0,NaN,NaN,NaN
128,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,4,Mandeep Singh,...,0,0,0,0,2,0,2,NaN,NaN,NaN
129,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,5,Mandeep Singh,...,0,0,0,0,4,0,4,NaN,NaN,NaN
130,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,6,Mandeep Singh,...,0,0,0,0,4,0,4,NaN,NaN,NaN
131,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,1,CH Gayle,...,0,0,0,0,0,0,0,NaN,NaN,NaN
132,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,2,CH Gayle,...,0,0,0,0,0,0,0,NaN,NaN,NaN
133,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,3,CH Gayle,...,0,0,0,0,1,0,1,NaN,NaN,NaN
134,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,4,Mandeep Singh,...,0,0,0,0,0,0,0,NaN,NaN,NaN
135,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,5,Mandeep Singh,...,0,0,0,0,0,0,0,NaN,NaN,NaN
136,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,6,Mandeep Singh,...,0,0,0,0,0,0,0,NaN,NaN,NaN
137,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,3,1,CH Gayle,...,0,0,0,0,0,0,0,NaN,NaN,NaN
138,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,3,2,CH Gayle,...,0,0,0,0,4,0,4,NaN,NaN,NaN
139,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,3,3,CH Gayle,...,0,0,0,0,1,0,1,NaN,NaN,NaN
140,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,3,4,Mandeep Singh,...,0,0,0,0,4,0,4,NaN,NaN,NaN
141,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,3,5,Mandeep Singh,...,0,0,0,0,1,0,1,NaN,NaN,NaN
142,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,3,6,CH Gayle,...,0,0,0,0,6,0,6,NaN,NaN,NaN
143,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,1,Mandeep Singh,...,0,0,0,0,1,0,1,NaN,NaN,NaN
144,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,2,CH Gayle,...,0,0,0,0,6,0,6,NaN,NaN,NaN
145,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,3,CH Gayle,...,0,0,0,0,2,0,2,NaN,NaN,NaN
146,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,4,CH Gayle,...,0,0,0,0,0,1,1,NaN,NaN,NaN
147,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,5,CH Gayle,...,0,0,0,0,0,0,0,NaN,NaN,NaN
148,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,6,CH Gayle,...,0,0,0,0,1,0,1,NaN,NaN,NaN
149,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,7,Mandeep Singh,...,0,0,0,0,4,0,4,NaN,NaN,NaN
150,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,5,1,CH Gayle,...,0,0,0,0,0,0,0,NaN,NaN,NaN
151,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,5,2,CH Gayle,...,0,0,0,0,0,0,0,NaN,NaN,NaN
152,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,5,3,CH Gayle,...,0,0,0,0,0,0,0,NaN,NaN,NaN
153,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,5,4,CH Gayle,...,0,0,0,0,0,1,1,NaN,NaN,NaN
154,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,5,5,CH Gayle,...,0,0,0,0,0,0,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149548,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,16,1,DJ Bravo,...,0,0,0,0,6,0,6,NaN,NaN,NaN
149549,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,16,2,DJ Bravo,...,0,0,0,0,1,0,1,NaN,NaN,NaN
149550,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,16,3,SR Watson,...,0,0,0,0,4,0,4,NaN,NaN,NaN
149551,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,16,4,SR Watson,...,0,0,0,0,4,0,4,NaN,NaN,NaN
149552,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,16,5,SR Watson,...,0,0,0,0,4,0,4,NaN,NaN,NaN
149553,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,16,6,SR Watson,...,0,0,0,0,1,0,1,NaN,NaN,NaN
149554,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,17,1,SR Watson,...,0,0,0,0,1,0,1,NaN,NaN,NaN
149555,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,17,2,DJ Bravo,...,0,0,0,0,1,0,1,NaN,NaN,NaN
149556,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,17,3,SR Watson,...,0,0,0,0,0,0,0,NaN,NaN,NaN
149557,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,17,4,SR Watson,...,0,0,0,0,0,0,0,NaN,NaN,NaN
149558,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,17,5,SR Watson,...,1,0,0,0,1,1,2,NaN,NaN,NaN
149559,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,17,6,DJ Bravo,...,0,0,0,0,1,0,1,NaN,NaN,NaN
149560,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,18,1,DJ Bravo,...,0,0,0,0,1,0,1,NaN,NaN,NaN
149561,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,18,2,SR Watson,...,0,0,0,0,6,0,6,NaN,NaN,NaN
149562,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,18,3,SR Watson,...,0,0,0,0,6,0,6,NaN,NaN,NaN
149563,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,18,4,SR Watson,...,0,0,0,0,6,0,6,NaN,NaN,NaN
149564,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,18,5,SR Watson,...,0,0,0,0,0,0,0,NaN,NaN,NaN
149565,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,18,6,SR Watson,...,0,0,0,0,1,0,1,NaN,NaN,NaN
149566,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,19,1,SR Watson,...,0,0,0,0,1,0,1,NaN,NaN,NaN
149567,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,19,2,DJ Bravo,...,0,0,0,0,0,0,0,DJ Bravo,caught,Q de Kock
149568,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,19,3,RA Jadeja,...,0,0,0,0,2,0,2,NaN,NaN,NaN
149569,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,19,4,RA Jadeja,...,0,0,0,0,0,0,0,NaN,NaN,NaN
149570,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,19,5,RA Jadeja,...,0,0,0,0,2,0,2,NaN,NaN,NaN
149571,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,19,6,RA Jadeja,...,4,0,0,0,4,4,8,NaN,NaN,NaN
149572,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,1,SR Watson,...,0,0,0,0,1,0,1,NaN,NaN,NaN
149573,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,...,0,0,0,0,1,0,1,NaN,NaN,NaN
149574,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,...,0,0,0,0,2,0,2,NaN,NaN,NaN
149575,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
149576,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,...,0,0,0,0,2,0,2,NaN,NaN,NaN
149577,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [21]:
delivery_df['current_score'] = delivery_df.groupby('match_id').cumsum()['total_runs_y']

In [22]:
delivery_df['runs_left'] = delivery_df['total_runs_x'] - delivery_df['current_score']

In [23]:
delivery_df['balls_left'] = 126 - (delivery_df['over']*6 + delivery_df['ball'])

In [24]:
delivery_df

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,penalty_runs,batsman_runs,extra_runs,total_runs_y,player_dismissed,dismissal_kind,fielder,current_score,runs_left,balls_left
125,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,...,0,1,0,1,NaN,NaN,NaN,1,206,119
126,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,Mandeep Singh,...,0,0,0,0,NaN,NaN,NaN,1,206,118
127,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,3,Mandeep Singh,...,0,0,0,0,NaN,NaN,NaN,1,206,117
128,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,4,Mandeep Singh,...,0,2,0,2,NaN,NaN,NaN,3,204,116
129,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,5,Mandeep Singh,...,0,4,0,4,NaN,NaN,NaN,7,200,115
130,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,6,Mandeep Singh,...,0,4,0,4,NaN,NaN,NaN,11,196,114
131,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,1,CH Gayle,...,0,0,0,0,NaN,NaN,NaN,11,196,113
132,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,2,CH Gayle,...,0,0,0,0,NaN,NaN,NaN,11,196,112
133,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,3,CH Gayle,...,0,1,0,1,NaN,NaN,NaN,12,195,111
134,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,4,Mandeep Singh,...,0,0,0,0,NaN,NaN,NaN,12,195,110
135,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,5,Mandeep Singh,...,0,0,0,0,NaN,NaN,NaN,12,195,109
136,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,2,6,Mandeep Singh,...,0,0,0,0,NaN,NaN,NaN,12,195,108
137,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,3,1,CH Gayle,...,0,0,0,0,NaN,NaN,NaN,12,195,107
138,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,3,2,CH Gayle,...,0,4,0,4,NaN,NaN,NaN,16,191,106
139,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,3,3,CH Gayle,...,0,1,0,1,NaN,NaN,NaN,17,190,105
140,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,3,4,Mandeep Singh,...,0,4,0,4,NaN,NaN,NaN,21,186,104
141,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,3,5,Mandeep Singh,...,0,1,0,1,NaN,NaN,NaN,22,185,103
142,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,3,6,CH Gayle,...,0,6,0,6,NaN,NaN,NaN,28,179,102
143,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,1,Mandeep Singh,...,0,1,0,1,NaN,NaN,NaN,29,178,101
144,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,2,CH Gayle,...,0,6,0,6,NaN,NaN,NaN,35,172,100
145,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,3,CH Gayle,...,0,2,0,2,NaN,NaN,NaN,37,170,99
146,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,4,CH Gayle,...,0,0,1,1,NaN,NaN,NaN,38,169,98
147,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,5,CH Gayle,...,0,0,0,0,NaN,NaN,NaN,38,169,97
148,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,6,CH Gayle,...,0,1,0,1,NaN,NaN,NaN,39,168,96
149,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,4,7,Mandeep Singh,...,0,4,0,4,NaN,NaN,NaN,43,164,95
150,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,5,1,CH Gayle,...,0,0,0,0,NaN,NaN,NaN,43,164,95
151,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,5,2,CH Gayle,...,0,0,0,0,NaN,NaN,NaN,43,164,94
152,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,5,3,CH Gayle,...,0,0,0,0,NaN,NaN,NaN,43,164,93
153,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,5,4,CH Gayle,...,0,0,1,1,NaN,NaN,NaN,44,163,92
154,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,5,5,CH Gayle,...,0,0,0,0,NaN,NaN,NaN,44,163,91
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149548,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,16,1,DJ Bravo,...,0,6,0,6,NaN,NaN,NaN,98,54,29
149549,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,16,2,DJ Bravo,...,0,1,0,1,NaN,NaN,NaN,99,53,28
149550,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,16,3,SR Watson,...,0,4,0,4,NaN,NaN,NaN,103,49,27
149551,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,16,4,SR Watson,...,0,4,0,4,NaN,NaN,NaN,107,45,26
149552,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,16,5,SR Watson,...,0,4,0,4,NaN,NaN,NaN,111,41,25
149553,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,16,6,SR Watson,...,0,1,0,1,NaN,NaN,NaN,112,40,24
149554,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,17,1,SR Watson,...,0,1,0,1,NaN,NaN,NaN,113,39,23
149555,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,17,2,DJ Bravo,...,0,1,0,1,NaN,NaN,NaN,114,38,22
149556,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,17,3,SR Watson,...,0,0,0,0,NaN,NaN,NaN,114,38,21
149557,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,17,4,SR Watson,...,0,0,0,0,NaN,NaN,NaN,114,38,20
149558,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,17,5,SR Watson,...,0,1,1,2,NaN,NaN,NaN,116,36,19
149559,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,17,6,DJ Bravo,...,0,1,0,1,NaN,NaN,NaN,117,35,18
149560,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,18,1,DJ Bravo,...,0,1,0,1,NaN,NaN,NaN,118,34,17
149561,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,18,2,SR Watson,...,0,6,0,6,NaN,NaN,NaN,124,28,16
149562,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,18,3,SR Watson,...,0,6,0,6,NaN,NaN,NaN,130,22,15
149563,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,18,4,SR Watson,...,0,6,0,6,NaN,NaN,NaN,136,16,14
149564,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,18,5,SR Watson,...,0,0,0,0,NaN,NaN,NaN,136,16,13
149565,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,18,6,SR Watson,...,0,1,0,1,NaN,NaN,NaN,137,15,12
149566,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,19,1,SR Watson,...,0,1,0,1,NaN,NaN,NaN,138,14,11
149567,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,19,2,DJ Bravo,...,0,0,0,0,DJ Bravo,caught,Q de Kock,138,14,10
149568,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,19,3,RA Jadeja,...,0,2,0,2,NaN,NaN,NaN,140,12,9
149569,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,19,4,RA Jadeja,...,0,0,0,0,NaN,NaN,NaN,140,12,8
149570,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,19,5,RA Jadeja,...,0,2,0,2,NaN,NaN,NaN,142,10,7
149571,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,19,6,RA Jadeja,...,0,4,4,8,NaN,NaN,NaN,150,2,6
149572,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,1,SR Watson,...,0,1,0,1,NaN,NaN,NaN,151,1,5
149573,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,...,0,1,0,1,NaN,NaN,NaN,152,0,4
149574,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,...,0,2,0,2,NaN,NaN,NaN,154,-2,3
149575,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,...,0,1,0,1,SR Watson,run out,KH Pandya,155,-3,2
149576,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,...,0,2,0,2,NaN,NaN,NaN,157,-5,1
149577,11415,Hyderabad,Mumbai Indians,152,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,...,0,0,0,0,SN Thakur,lbw,NaN,157,-5,0

In [25]:
delivery_df['player_dismissed'] = delivery_df['player_dismissed'].fillna("0")
delivery_df['player_dismissed'] = delivery_df['player_dismissed'].apply(lambda x:x if x == "0" else "1")
delivery_df['player_dismissed'] = delivery_df['player_dismissed'].astype('int')
wickets = delivery_df.groupby('match_id').cumsum()['player_dismissed'].values
delivery_df['wickets'] = 10 - wickets
delivery_df.head()

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,batsman_runs,extra_runs,total_runs_y,player_dismissed,dismissal_kind,fielder,current_score,runs_left,balls_left,wickets
125,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,...,1,0,1,0,NaN,NaN,1,206,119,10
126,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,Mandeep Singh,...,0,0,0,0,NaN,NaN,1,206,118,10
127,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,3,Mandeep Singh,...,0,0,0,0,NaN,NaN,1,206,117,10
128,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,4,Mandeep Singh,...,2,0,2,0,NaN,NaN,3,204,116,10
129,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,5,Mandeep Singh,...,4,0,4,0,NaN,NaN,7,200,115,10

In [26]:
delivery_df.head()

,match_id,city,winner,total_runs_x,inning,batting_team,bowling_team,over,ball,batsman,...,batsman_runs,extra_runs,total_runs_y,player_dismissed,dismissal_kind,fielder,current_score,runs_left,balls_left,wickets
125,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,1,CH Gayle,...,1,0,1,0,NaN,NaN,1,206,119,10
126,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,2,Mandeep Singh,...,0,0,0,0,NaN,NaN,1,206,118,10
127,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,3,Mandeep Singh,...,0,0,0,0,NaN,NaN,1,206,117,10
128,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,4,Mandeep Singh,...,2,0,2,0,NaN,NaN,3,204,116,10
129,1,Hyderabad,Sunrisers Hyderabad,207,2,Royal Challengers Bangalore,Sunrisers Hyderabad,1,5,Mandeep Singh,...,4,0,4,0,NaN,NaN,7,200,115,10

In [27]:
# crr = runs/overs
delivery_df['crr'] = (delivery_df['current_score']*6)/(120 - delivery_df['balls_left'])

In [28]:
delivery_df['rrr'] = (delivery_df['runs_left']*6)/delivery_df['balls_left']

In [29]:
def result(row):
    return 1 if row['batting_team'] == row['winner'] else 0

In [30]:
delivery_df['result'] = delivery_df.apply(result,axis=1)

In [31]:
final_df = delivery_df[['batting_team','bowling_team','city','runs_left','balls_left','wickets','total_runs_x','crr','rrr','result']]

In [32]:
final_df = final_df.sample(final_df.shape[0])

In [33]:
final_df.sample()

,batting_team,bowling_team,city,runs_left,balls_left,wickets,total_runs_x,crr,rrr,result
29301,Deccan Chargers,Delhi Daredevils,Durban,140,103,10,173,11.647059,8.15534,0

In [34]:
final_df.dropna(inplace=True)

In [35]:
final_df = final_df[final_df['balls_left'] != 0]

In [36]:
X = final_df.iloc[:,:-1]
y = final_df.iloc[:,-1]
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [37]:
X_train

,batting_team,bowling_team,city,runs_left,balls_left,wickets,total_runs_x,crr,rrr
133761,Kolkata Knight Riders,Sunrisers Hyderabad,Hyderabad,17,15,7,183,9.485714,6.800000
50604,Kolkata Knight Riders,Rajasthan Royals,Kolkata,42,67,8,81,4.415094,3.761194
34317,Kolkata Knight Riders,Royal Challengers Bangalore,Kolkata,1,7,7,135,7.115044,0.857143
27891,Chennai Super Kings,Rajasthan Royals,Kimberley,76,62,8,140,6.620690,7.354839
11730,Delhi Daredevils,Chennai Super Kings,Chennai,71,70,10,169,11.760000,6.085714
106564,Kings XI Punjab,Chennai Super Kings,Chennai,123,45,3,192,5.520000,16.400000
66139,Kings XI Punjab,Royal Challengers Bangalore,Bangalore,99,81,9,158,9.076923,7.333333
36690,Royal Challengers Bangalore,Mumbai Indians,Mumbai,3,8,7,151,7.928571,2.250000
70562,Deccan Chargers,Rajasthan Royals,Hyderabad,8,13,6,126,6.616822,3.692308
59674,Kolkata Knight Riders,Rajasthan Royals,Jaipur,95,55,5,164,6.369231,10.363636
53071,Kolkata Knight Riders,Kings XI Punjab,Kolkata,24,35,8,119,6.705882,4.114286
102662,Sunrisers Hyderabad,Royal Challengers Bangalore,Bangalore,50,45,8,166,9.280000,6.666667
136880,Royal Challengers Bangalore,Mumbai Indians,Bengaluru,121,65,8,197,8.290909,11.169231
63510,Kings XI Punjab,Mumbai Indians,Mumbai,60,35,8,163,7.270588,10.285714
101662,Sunrisers Hyderabad,Chennai Super Kings,Chennai,124,56,8,209,7.968750,13.285714
134404,Chennai Super Kings,Sunrisers Hyderabad,Mumbai,147,114,9,148,1.000000,7.736842
104355,Kolkata Knight Riders,Kings XI Punjab,Pune,78,55,5,155,7.107692,8.509091
42468,Rajasthan Royals,Kings XI Punjab,Jaipur,148,116,10,153,7.500000,7.655172
116159,Mumbai Indians,Royal Challengers Bangalore,Mumbai,27,23,6,170,8.845361,7.043478
65468,Mumbai Indians,Deccan Chargers,Mumbai,37,50,7,100,5.400000,4.440000
143168,Sunrisers Hyderabad,Chennai Super Kings,Hyderabad,115,106,10,139,10.285714,6.509434
42475,Rajasthan Royals,Kings XI Punjab,Jaipur,139,110,10,153,8.400000,7.581818
10546,Royal Challengers Bangalore,Chennai Super Kings,Bangalore,48,32,7,178,8.863636,9.000000
51089,Rajasthan Royals,Kings XI Punjab,Chandigarh,96,41,5,195,7.518987,14.048780
84009,Mumbai Indians,Sunrisers Hyderabad,Mumbai,79,41,7,178,7.518987,11.560976
13146,Deccan Chargers,Chennai Super Kings,Chennai,72,68,9,144,8.307692,6.352941
18432,Chennai Super Kings,Rajasthan Royals,Chennai,198,112,10,211,9.750000,10.607143
78231,Chennai Super Kings,Sunrisers Hyderabad,Chennai,150,110,10,159,5.400000,8.181818
129671,Kolkata Knight Riders,Mumbai Indians,Mumbai,102,69,8,187,10.000000,8.869565
40781,Royal Challengers Bangalore,Kings XI Punjab,Chandigarh,134,86,9,181,8.294118,9.348837
...,...,...,...,...,...,...,...,...,...
100227,Chennai Super Kings,Mumbai Indians,Mumbai,2,10,7,173,9.327273,1.200000
78062,Mumbai Indians,Kolkata Knight Riders,Kolkata,48,37,7,159,8.024096,7.783784
115205,Kolkata Knight Riders,Sunrisers Hyderabad,Hyderabad,30,29,8,142,7.384615,6.206897
99490,Kings XI Punjab,Delhi Daredevils,Chandigarh,54,76,8,115,8.318182,4.263158
139342,Kolkata Knight Riders,Royal Challengers Bangalore,Bengaluru,130,73,9,210,10.212766,10.684932
111323,Rajasthan Royals,Chennai Super Kings,Chennai,130,92,10,157,5.785714,8.478261
59454,Deccan Chargers,Chennai Super Kings,Visakhapatnam,99,46,6,193,7.621622,12.913043
4330,Kolkata Knight Riders,Sunrisers Hyderabad,Hyderabad,198,110,9,209,6.600000,10.800000
86068,Rajasthan Royals,Sunrisers Hyderabad,Delhi,24,19,4,132,6.415842,7.578947
8364,Rajasthan Royals,Kings XI Punjab,Jaipur,137,101,8,166,9.157895,8.138614
75618,Kolkata Knight Riders,Kings XI Punjab,Chandigarh,95,76,8,157,8.454545,7.500000
130170,Royal Challengers Bangalore,Sunrisers Hyderabad,Hyderabad,73,54,6,155,7.454545,8.111111
65706,Kolkata Knight Riders,Chennai Super Kings,Chennai,66,55,9,139,6.738462,7.200000
19244,Rajasthan Royals,Mumbai Indians,Jaipur,68,48,5,145,6.416667,8.500000
77347,Delhi Daredevils,Mumbai Indians,Delhi,27,34,10,161,9.348837,4.764706
114661,Mumbai Indians,Kolkata Knight Riders,Kolkata,187,118,10,187,0.000000,9.508475
86255,Mumbai Indians,Rajasthan Royals,Kolkata,112,76,10,165,7.227273,8.842105
123092,Royal Challengers Bangalore,Kings XI Punjab,Bengaluru,106,77,8,161,7.674419,8.259740
44192,Rajasthan Royals,Mumbai Indians,Jaipur,130,75,6,174,5.866667,10.400000
69059,Mumbai Indians,Royal Challengers Bangalore,Bangalore,126,71,6,171,5.510204,10.647887
47268,Deccan Chargers,Chennai Super Kings,Mumbai,140,108,10,142,1.000000,7.777778
33023,Royal Challengers Bangalore,Chennai Super Kings,Johannesburg,64,59,8,146,8.065574,6.508475
127205,Kolkata Knight Riders,Delhi Daredevils,Delhi,181,94,7,223,9.692308,11.553191
21087,Royal Challengers Bangalore,Chennai Super Kings,Port Elizabeth,119,56,5,179,5.625000,12.750000
48729,Deccan Chargers,Kolkata Knight Riders,Kolkata,75,36,5,163,6.285714,12.500000
60352,Delhi Daredevils,Chennai Super Kings,Delhi,98,115,10,110,14.400000,5.113043
91943,Rajasthan Royals,Delhi Daredevils,Delhi,125,95,9,152,6.480000,7.894737
38855,Royal Challengers Bangalore,Delhi Daredevils,Bangalore,97,55,7,183,7.938462,10.581818
49625,Royal Challengers Bangalore,Deccan Chargers,Hyderabad,155,101,8,175,6.315789,9.207921
138415,Delhi Capitals,Kings XI Punjab,Mohali,21,21,7,175,9.333333,6.000000

In [38]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

trf = ColumnTransformer([
    ('trf',OneHotEncoder(sparse=False,drop='first'),['batting_team','bowling_team','city'])
]
,remainder='passthrough')

ModuleNotFoundError: No module named 'sklearn.compose'

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline

In [ ]:
pipe = Pipeline(steps=[
    ('step1',trf),
    ('step2',LogisticRegression(solver='liblinear'))
])

In [39]:
pipe.fit(X_train,y_train)

NameError: name 'pipe' is not defined

In [40]:
y_pred = pipe.predict(X_test)

NameError: name 'pipe' is not defined

In [41]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

NameError: name 'y_pred' is not defined

In [42]:
pipe.predict_proba(X_test)[10]

NameError: name 'pipe' is not defined

In [43]:
def match_summary(row):
    print("Batting Team-" + row['batting_team'] + " | Bowling Team-" + row['bowling_team'] + " | Target- " + str(row['total_runs_x']))

In [44]:
def match_progression(x_df,match_id,pipe):
    match = x_df[x_df['match_id'] == match_id]
    match = match[(match['ball'] == 6)]
    temp_df = match[['batting_team','bowling_team','city','runs_left','balls_left','wickets','total_runs_x','crr','rrr']].dropna()
    temp_df = temp_df[temp_df['balls_left'] != 0]
    result = pipe.predict_proba(temp_df)
    temp_df['lose'] = np.round(result.T[0]*100,1)
    temp_df['win'] = np.round(result.T[1]*100,1)
    temp_df['end_of_over'] = range(1,temp_df.shape[0]+1)
    
    target = temp_df['total_runs_x'].values[0]
    runs = list(temp_df['runs_left'].values)
    new_runs = runs[:]
    runs.insert(0,target)
    temp_df['runs_after_over'] = np.array(runs)[:-1] - np.array(new_runs)
    wickets = list(temp_df['wickets'].values)
    new_wickets = wickets[:]
    new_wickets.insert(0,10)
    wickets.append(0)
    w = np.array(wickets)
    nw = np.array(new_wickets)
    temp_df['wickets_in_over'] = (nw - w)[0:temp_df.shape[0]]
    
    print("Target-",target)
    temp_df = temp_df[['end_of_over','runs_after_over','wickets_in_over','lose','win']]
    return temp_df,target

In [45]:
temp_df,target = match_progression(delivery_df,74,pipe)
temp_df

NameError: name 'pipe' is not defined

In [46]:
import matplotlib.pyplot as plt
plt.figure(figsize=(18,8))
plt.plot(temp_df['end_of_over'],temp_df['wickets_in_over'],color='yellow',linewidth=3)
plt.plot(temp_df['end_of_over'],temp_df['win'],color='#00a65a',linewidth=4)
plt.plot(temp_df['end_of_over'],temp_df['lose'],color='red',linewidth=4)
plt.bar(temp_df['end_of_over'],temp_df['runs_after_over'])
plt.title('Target-' + str(target))

NameError: name 'temp_df' is not defined

In [ ]:
teams

In [ ]:
delivery_df['city'].unique()

In [47]:
import pickle
pickle.dump(pipe,open('pipe.pkl','wb'))

NameError: name 'pipe' is not defined